services:
  ros2-perf-multihost-builder:
    image: ghcr.io/hal-lab-u-tokyo/ros2-perf-multihost:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      labels:
        - "org.opencontainers.image.source=https://github.com/hal-lab-u-tokyo/ros2-perf-multihost"
